sudo: required
lenguaje: node_js
node_js:  "12"
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  - npm install
script:
  - npm build
  - docker build -t rafaelrb40/strore:store-back .
  - docker tag rafaelrb40/store:store-back registry.heroku.com/storebac/web


deploy:
  provider: script
  script:
    docker push rafaelrb40/store:store-back;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master



