language: node_js
node_js:
  - "13.12.0"
before_install: cd ./Proyectos_integracion/store-back
cache:
directories:
    - ./STORE-BACK/node_modules
install:
    - npm install
script:
    - npm run-script build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: STORE-BACK/dist/
    on:
        branch: master
